LBCORE-591 Added command to query DB without credentials
git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@180624 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: 3d8774e04f7e2dcc0f0f4f0b07612470b382e313

diff --git a/LbScripts/LbRelease/scripts/lb-sdb-query b/LbScripts/LbRelease/scripts/lb-sdb-query
--- a/LbScripts/LbRelease/scripts/lb-sdb-query
+++ b/LbScripts/LbRelease/scripts/lb-sdb-query
@@ -1,5 +1,19 @@
 #!/bin/sh
 
-. lb-sdb-env.sh
-python ${LBRELEASEROOT}/python/LbRelease/SoftConfDB/LbSdbQuery.py $@
-lb-sdb-clearenv.sh
+# First checking if we run in readonly mode
+# In this case no need to get the credentials...
+
+runreadonly=`echo $@ | grep -c '\-\-readonly'`
+if [ $runreadonly -eq 1 ]; then
+    # In this case we setup the env but no need to call the SSO
+    . SetupProject.sh --silent Tools --use Ariadne
+    if [ "$SetupProjectStatus" != 0 ] ; then
+        echo "ERROR: Cannot prepare the environment to use Ariadne."
+        exit 1
+    fi
+    python ${LBRELEASEROOT}/python/LbRelease/SoftConfDB/LbSdbQuery.py $@
+else
+    . lb-sdb-env.sh
+    python ${LBRELEASEROOT}/python/LbRelease/SoftConfDB/LbSdbQuery.py $@
+    lb-sdb-clearenv.sh
+fi
