Added check of apps used by DIRAC steps
git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@158238 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: 75628172aac1f3a3d3191f61afaf852e508795ec

diff --git a/LbScripts/LbLegacy/scripts/archive_project b/LbScripts/LbLegacy/scripts/archive_project
--- a/LbScripts/LbLegacy/scripts/archive_project
+++ b/LbScripts/LbLegacy/scripts/archive_project
@@ -85,6 +85,13 @@ if !(-r ${rel_dir}/$PACKAGE/$VERSION) then
    exit 0
 endif
 
+# Checking if there are still DIRAC active steps
+lb-dirac-check-app-use $project $version
+if ( $? == 1 ) then
+	echo "Project $project $version is used in a DIRAC Usable step and cannot be archived"
+    exit 1
+endif
+
 # Archiving the distribution files
 echo "===> Archiving the distribution files"
 lb-project-archive-dist $project $version
