Added the macro Package_failure_policy
git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@13860 4525493e-7705-40b1-a816-d608a930855b

diff --git a/LbScripts/LbUtils/data/Makefile b/LbScripts/LbUtils/data/Makefile
--- a/LbScripts/LbUtils/data/Makefile
+++ b/LbScripts/LbUtils/data/Makefile
@@ -1,4 +1,4 @@
-# $Id: Makefile,v 1.4 2009-07-22 20:01:56 marcocle Exp $
+# $Id: Makefile,v 1.5 2009-07-28 13:33:34 marcocle Exp $
 ################################################################################
 #
 # Generic Makefile for CMT projects.
@@ -44,6 +44,30 @@ endef
 define clean_banner
 echo "#==== Cleaning package $(1)"
 endef
+
+# -- Special macro to change the behavior on a failure of a package
+#    (complementary to the option '-k')
+#  Allowed values for Package_failure_policy:
+#    stop:   do not continue (default)
+#    next:   if a group fails, continue with the next package
+#    ignore: try all the groups even if one fails before going to the next package
+#            (may result in duplicated errors within a package) 
+Package_failure_handler = test $$BUILD_RESULT -eq 0 || exit $$BUILD_RESULT ;
+ifdef Package_failure_policy
+ifeq ($(Package_failure_policy),stop)
+Package_failure_handler = test $$BUILD_RESULT -eq 0 || exit $$BUILD_RESULT ;
+else
+ifeq ($(Package_failure_policy),next)
+Package_failure_handler = test $$BUILD_RESULT -eq 0 || break ;
+else
+ifeq ($(Package_failure_policy),ignore)
+Package_failure_handler = 
+else
+$(error Unknown Package_failure_policy "$(Package_failure_policy)". Allowed values: "stop" (default), "ignore", "next")
+endif
+endif
+endif
+endif
 
 # Fix the separator for environment variables
 # (needed if the variables are specified as lists in Eclipse)
@@ -93,13 +117,13 @@ ifdef CMTUSERCONTEXT
 	for group in $(groups) ; do \
 		cmt make $$group 2>&1 | tee -a build.$(CMTCONFIG).log ; export BUILD_RESULT=$$PIPESTATUS \
 		date >> build.$(CMTCONFIG).log ; \
-		test $$BUILD_RESULT -eq 0 || exit $$BUILD_RESULT ; \
+		$(Package_failure_handler) \
 	done
 else
 	@for group in $(groups) ; do \
 		$(MAKE) -C $*/cmt $$group 2>&1 | tee -a $*/cmt/build.$(CMTCONFIG).log ; export BUILD_RESULT=$$PIPESTATUS \
 		date >> $*/cmt/build.$(CMTCONFIG).log ; \
-		test $$BUILD_RESULT -eq 0 || exit $$BUILD_RESULT ; \
+		$(Package_failure_handler) \
 	done
 endif
 
