added protection to avoid infinite recursion (if the target executable is not found)
git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@127775 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: 679ed0ea6ce9608766a6d9e328732245f3f30230

diff --git a/LbScripts/LbConfiguration/scripts/doxygen b/LbScripts/LbConfiguration/scripts/doxygen
--- a/LbScripts/LbConfiguration/scripts/doxygen
+++ b/LbScripts/LbConfiguration/scripts/doxygen
@@ -25,4 +25,13 @@ if [ "$SetupProjectStatus" != 0 ] ; then
     echo "ERROR: Cannot prepare the environment to use doxygen."
     exit 1
 fi
+
+# Prevent infinite recursion of the script if the gerenated
+# environment is frong (e.g. because of unsupported platform).
+if [ $0 == $(which doxygen) ] ; then
+    echo "ERROR: Cannot find Doxygen executable (unsupported platform?)"
+    exit 1
+fi
+
+
 doxygen "${args[@]}"
