added message in case of failure of the call to SetupProject.
git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@53587 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: f8dbba0a41481073df86060e2fcfa7ebd8e5d940

diff --git a/LbScripts/LbConfiguration/scripts/doxygen b/LbScripts/LbConfiguration/scripts/doxygen
--- a/LbScripts/LbConfiguration/scripts/doxygen
+++ b/LbScripts/LbConfiguration/scripts/doxygen
@@ -21,4 +21,8 @@ done
 args=( "$@" )
 shift $#
 . SetupProject.sh --silent LCGCMT $LCGCMT_VERSION doxygen $DOXYGEN_VERSION
+if [ "$SetupProjectStatus" != 0 ] ; then
+    echo "ERROR: Cannot prepare the environment to use doxygen."
+    exit 1
+fi
 doxygen "${args[@]}"
