Fixes to LbConfiguration/scripts/eclipse
- do not set $JYTHONPATH (done in the requirements of the Eclipse
package)
- added a hack to set the user name to the full name instead of the
login name.
- fixed the infinite recursion occurring when the Eclipse package is not
correctly installed.

Marco Clemencic <marco.clemencic@cern.ch>


git-svn-id: http://svn.cern.ch/guest/lhcb/LbScripts/trunk@125978 4525493e-7705-40b1-a816-d608a930855b

Former-commit-id: a38d2e80a17dd506946a79077179f60ef3f00bef

diff --git a/LbScripts/LbConfiguration/scripts/eclipse b/LbScripts/LbConfiguration/scripts/eclipse
--- a/LbScripts/LbConfiguration/scripts/eclipse
+++ b/LbScripts/LbConfiguration/scripts/eclipse
@@ -23,10 +23,18 @@ if [ "$SetupProjectStatus" != 0 ] ; then
     exit 1
 fi
 
-if [ -n "$JYPTHONPATH" ] ; then
-  export JYTHONPATH=${PYTHONPATH}:${JYTHONPATH}
-else 
-  export JYPTHONPATH=${PYTHONPATH}
+# get user real name
+if which getent > /dev/null 2>&1 ; then
+    un=$(getent passwd $USER | cut -d: -f5 | cut -d, -f1)
+else
+    un=$USER
 fi
 
-eclipse "${args[@]}"
+# Prevent infinite recursion of the script if the gerenated
+# environment is frong (e.g. because of unsupported platform).
+if [ $0 == $(which eclipse) ] ; then
+    echo "ERROR: Cannot find Eclipse executable (unsupported platform?)"
+    exit 1
+fi
+
+eclipse "${args[@]}" -vmargs -Dpython.home="__pyclasspath__" -Duser.name="$un"
